from _lib import enrich

# ── 南北朝 ──────────────────────────────────────────────────────────────────
enrich(
    "nan-bei-chao.json",
    person_content={
        "tan-dao-ji": "檀道济（？—436年），刘宋名将，北府兵重要将领。随刘裕北伐，收复洛阳、长安，功勋卓著。后镇守边疆，威名远震。宋文帝猜忌其功高，以谋反罪将其杀害。檀道济临刑前怒曰：「乃坏汝万里长城！」自毁长城的典故由此而来。",
        "chen-qing-zhi": "陈庆之（484—539年），南朝梁名将。以七千白袍军北伐，连克三十二城，四十七战皆捷，一度攻入洛阳。北方民谣唱道：「名师大将莫自牢，千军万马避白袍。」陈庆之是中国历史上最杰出的将领之一，创造了军事史上的奇迹。",
        "gao-chang-gong": "高长恭（541—573年），北齐名将，兰陵王。貌美如冠玉，恐不足以威敌，每次作战都戴狰狞面具。邙山之战中率五百骑兵冲入敌阵，大败北周军队。后因功高震主，被北齐后主赐毒酒而死。兰陵王是中国历史上最著名的美男子将领，后世创作《兰陵王入阵曲》纪念他。",
        "lv-lv-guang": "斛律光（515—572年），北齐名将，落雁都督。骁勇善战，箭术超群，多次击败北周军队。后被北齐后主猜忌，以谋反罪杀害。斛律光之死，北周武帝大喜，下令大赦，曰：「此人若在，朕岂能至邺！」北齐自毁长城，加速了灭亡。",
        "yu-wen-yong": "宇文邕（543—578年），北周武帝，宇文泰之子。即位后诛杀权臣宇文护，亲掌朝政。推行改革，灭佛兴儒，发展经济。577年灭北齐，统一北方，为隋朝统一全国奠定基础。宇文邕是南北朝最杰出的帝王之一，可惜英年早逝。",
        "xi-fu-ren": "冼夫人（512—602年），高凉人，岭南少数民族首领，「岭南圣母」。历经梁、陈、隋三朝，维护岭南和平稳定，促进民族融合。隋朝统一后，冼夫人率岭南归附，被封为谯国夫人。冼夫人是中国历史上最杰出的少数民族领袖之一，被誉为「岭南圣母」。",
        "su-chuo": "苏绰（498—546年），西魏改革家、政治家。辅佐宇文泰推行改革，制定《六条诏书》，改革官制、发展经济、整顿军队。苏绰的改革为西魏、北周的强盛奠定了基础，也为隋唐制度的形成产生了深远影响。",
    },
    new_persons=[
        {"slug": "tan-dao-ji", "name": "檀道济", "primaryRole": "general",
         "roles": ["general", "hero"], "importance": 80, "deathYear": 436,
         "aliases": ["万里长城"],
         "summary": "刘宋名将，功高震主被杀，自毁长城典故由来。"},
        {"slug": "chen-qing-zhi", "name": "陈庆之", "primaryRole": "general",
         "roles": ["general"], "importance": 90, "birthYear": 484,
         "deathYear": 539, "aliases": ["白袍将军"],
         "summary": "南朝梁名将，七千白袍军北伐，四十七战皆捷，攻入洛阳。"},
        {"slug": "gao-chang-gong", "name": "高长恭", "primaryRole": "general",
         "roles": ["general", "prince"], "importance": 85, "birthYear": 541,
         "deathYear": 573, "aliases": ["兰陵王"],
         "summary": "北齐名将，兰陵王，貌美戴面具作战，邙山之战大败北周。"},
        {"slug": "lv-lv-guang", "name": "斛律光", "primaryRole": "general",
         "roles": ["general"], "importance": 80, "birthYear": 515,
         "deathYear": 572, "aliases": ["落雁都督"],
         "summary": "北齐名将，骁勇善战，被后主猜忌杀害，北齐自毁长城。"},
        {"slug": "yu-wen-yong", "name": "宇文邕", "primaryRole": "emperor",
         "roles": ["emperor", "reformer"], "importance": 90, "birthYear": 543,
         "deathYear": 578, "aliases": ["北周武帝"],
         "summary": "北周武帝，诛杀权臣，灭佛兴儒，灭北齐统一北方。"},
        {"slug": "xi-fu-ren", "name": "冼夫人", "primaryRole": "leader",
         "roles": ["leader", "hero"], "importance": 80, "birthYear": 512,
         "deathYear": 602, "aliases": ["岭南圣母", "谯国夫人"],
         "summary": "岭南少数民族首领，历经三朝，维护岭南和平，促进民族融合。"},
        {"slug": "su-chuo", "name": "苏绰", "primaryRole": "reformer",
         "roles": ["reformer", "minister"], "importance": 75, "birthYear": 498,
         "deathYear": 546, "aliases": ["苏令绰"],
         "summary": "西魏改革家，制定六条诏书，为北周强盛奠定基础。"},
    ],
    new_events=[
        {"slug": "chen-qing-zhi-bei-fa", "name": "陈庆之北伐", "timeStart": 528,
         "timeEnd": 529, "aliases": ["白袍军北伐"],
         "summary": "陈庆之率七千白袍军北伐，连克三十二城，四十七战皆捷。",
         "content": "公元528年，南朝梁将领陈庆之率七千白袍军北伐，护送北海王元颢北归争夺帝位。陈庆之连克三十二城，四十七战皆捷，一度攻入北魏都城洛阳。北方民谣唱道：「名师大将莫自牢，千军万马避白袍。」后因孤军深入、后援不继，被迫南撤。陈庆之北伐是中国军事史上的奇迹，以七千人横扫北魏，创造了以少胜多的神话。"},
        {"slug": "bei-zhou-mie-bei-qi", "name": "北周灭北齐", "timeStart": 576,
         "timeEnd": 577, "aliases": ["北周统一北方"],
         "summary": "北周武帝宇文邕率军灭北齐，统一北方，为隋朝统一奠定基础。",
         "content": "公元576年，北周武帝宇文邕率军伐齐，攻占北齐重镇晋阳。次年攻入北齐都城邺城，北齐后主被俘，北齐灭亡。北周统一北方后，又灭南朝陈，为隋朝统一全国奠定了基础。北周灭北齐是南北朝时期最重要的历史事件之一，结束了北方长期分裂的局面。"},
        {"slug": "lan-ling-wang-ru-zhen-qu", "name": "兰陵王入阵曲", "timeStart": 564,
         "timeEnd": 564, "aliases": ["邙山之战"],
         "summary": "兰陵王高长恭邙山之战大败北周军队，后人创作《兰陵王入阵曲》纪念。",
         "content": "公元564年，北周军队进攻北齐，围攻洛阳。兰陵王高长恭率五百骑兵冲入敌阵，大败北周军队，解洛阳之围。将士们创作《兰陵王入阵曲》歌颂他的英勇。此曲后来传入日本，成为日本雅乐的重要曲目。兰陵王因功高震主，后被北齐后主赐毒酒而死，年仅三十二岁。"},
    ],
)

# ── 隋朝 ──────────────────────────────────────────────────────────────────────
enrich(
    "sui.json",
    person_content={
        "yuwen-hua-ji": "宇文化及（？—619年），隋朝权臣宇文述之子。618年江都兵变，宇文化及杀死隋炀帝，立秦王杨浩为帝，自任大丞相。后率军北归，被李密击败，又杀杨浩自立为帝，国号许。不久被窦建德擒杀。宇文化及是隋朝灭亡的直接推动者。",
        "di-rang": "翟让（？—617年），隋末瓦岗军创始人。东郡韦城人，原为法曹，因罪逃亡，于瓦岗寨聚众起义。后李密加入，势力大盛。翟让让位于李密，后被李密设计杀害。翟让是隋末农民起义的重要领袖。",
        "wang-shi-chong": "王世充（？—621年），隋末割据势力。西域胡人后裔，隋末任江都通守。宇文化及杀隋炀帝后，王世充击败李密，占据洛阳，自立为帝，国号郑。后被李世民击败，投降唐朝，后被仇人杀害。",
        "zhang-xu-tuo": "张须陀（565—616年），隋朝名将。骁勇善战，多次镇压农民起义，威震天下。后在与瓦岗军作战中，被李密设伏包围，力战而死。张须陀是隋朝最后一位名将，他的死标志着隋朝军事力量的崩溃。",
    },
    new_persons=[
        {"slug": "yuwen-hua-ji", "name": "宇文化及", "primaryRole": "rebel",
         "roles": ["rebel", "usurper"], "importance": 70, "deathYear": 619,
         "aliases": ["宇文化及"],
         "summary": "隋朝权臣，江都兵变杀隋炀帝，自立为帝，后被窦建德擒杀。"},
        {"slug": "di-rang", "name": "翟让", "primaryRole": "rebel",
         "roles": ["rebel", "leader"], "importance": 65, "deathYear": 617,
         "aliases": ["翟让"],
         "summary": "瓦岗军创始人，聚众起义，后让位于李密，被李密杀害。"},
        {"slug": "wang-shi-chong", "name": "王世充", "primaryRole": "warlord",
         "roles": ["warlord", "emperor"], "importance": 70, "deathYear": 621,
         "aliases": ["王世充"],
         "summary": "隋末割据势力，击败李密占据洛阳，自立为帝，后被李世民击败。"},
        {"slug": "zhang-xu-tuo", "name": "张须陀", "primaryRole": "general",
         "roles": ["general"], "importance": 75, "birthYear": 565,
         "deathYear": 616, "aliases": ["张须陀"],
         "summary": "隋朝名将，骁勇善战，威震天下，后被瓦岗军包围战死。"},
    ],
    new_events=[
        {"slug": "wa-gang-jun-qi-yi", "name": "瓦岗军起义", "timeStart": 611,
         "timeEnd": 618, "aliases": ["瓦岗军"],
         "summary": "翟让、李密领导的隋末最大义军，破洛口仓开仓济民，众至数十万。",
         "content": "611年翟让聚众瓦岗寨起兵，李密入伙后势力大盛，败隋名将张须陀、攻破洛口仓开仓放粮，归者如流、众至数十万，成为隋末反隋义军的中坚，一度推李密为魏公、盟主。后内讧与战败，瓦岗军瓦解，部众多归唐。瓦岗军起义是隋末农民起义中规模最大的一支，加速了隋朝的灭亡。"},
        {"slug": "jiang-du-bing-bian", "name": "江都兵变", "timeStart": 618,
         "timeEnd": 618, "aliases": ["宇文化及弑君"],
         "summary": "宇文化及发动兵变，杀死隋炀帝，隋朝名存实亡。",
         "content": "618年，隋炀帝巡幸江都（今扬州），随行禁军多为关中人，思乡心切。虎贲郎将司马德戡、元礼等人发动兵变，拥立宇文化及为主。宇文化及率军攻入宫中，杀死隋炀帝，立秦王杨浩为帝。江都兵变标志着隋朝的实质性灭亡，宇文化及后率军北归，被李密、窦建德先后击败。"},
    ],
)

# ── 唐朝 ──────────────────────────────────────────────────────────────────────
enrich(
    "tang.json",
    person_content={
        "du-ru-hui": "杜如晦（585—630年），字克明，唐朝开国功臣，凌烟阁二十四功臣之一。与房玄龄同为秦王府重要谋士，参与玄武门之变。房玄龄善谋、杜如晦善断，二人配合默契，时称「房谋杜断」。杜如晦是贞观之治的重要缔造者之一，可惜英年早逝，年仅四十六岁。",
        "yao-chong": "姚崇（651—721年），唐朝名相，开元盛世的主要缔造者。历仕武则天、唐睿宗、唐玄宗三朝，三次拜相。向唐玄宗提出「十事要说」，包括不贪边功、宦官不参政等，被采纳后推行改革，整顿吏治、发展经济，开创开元盛世。姚崇与宋璟并称「姚宋」，是唐代最杰出的宰相之一。",
        "song-jing": "宋璟（663—737年），唐朝名相，开元盛世的主要缔造者。为人刚正不阿、清廉自守，接替姚崇为相，继续推行改革。宋璟选拔人才不畏权贵，执法公正，朝野肃然。姚崇善应变、宋璟善守法，二人并称「姚宋」，共同开创了开元盛世。",
        "li-lin-fu": "李林甫（683—753年），唐朝权相，口蜜腹剑的典型。任相十九年，独揽朝政，排斥异己，堵塞言路。表面和善、内心阴险，「口有蜜、腹有剑」的成语由此而来。李林甫专权使唐朝政治日益腐败，为安史之乱埋下祸根。",
        "yang-guo-zhong": "杨国忠（？—756年），杨贵妃堂兄，唐朝权相。李林甫死后继任宰相，专权跋扈、结党营私。与安禄山争权，激化矛盾，导致安史之乱爆发。安史之乱后随唐玄宗逃往四川，途经马嵬坡被禁军杀死。",
        "gao-li-shi": "高力士（684—762年），唐朝宦官，唐玄宗最宠信的宦官。历经武则天、唐玄宗两朝，官至骠骑大将军。高力士虽为宦官，但颇有政治才能，多次参与重大决策。安史之乱后随唐玄宗流落，后被李辅国流放，忧愤而死。",
        "lai-jun-chen": "来俊臣（651—697年），唐朝酷吏，武则天时期最著名的酷吏。与周兴等人大兴告密之风，罗织罪名、严刑逼供，制造大量冤案。后因得罪武氏诸王和太平公主，被武则天处死。来俊臣与周兴是武则天时期恐怖政治的代表人物。",
        "zhang-xu": "张旭（约675—750年），字伯高，唐代著名书法家，「草圣」。精通草书，与怀素并称「颠张醉素」。张旭嗜酒，每醉后呼叫狂走，然后落笔，故称「张颠」。其草书气势磅礴、变幻莫测，对后世草书影响深远。与李白诗歌、裴旻剑舞并称「唐代三绝」。",
        "huai-su": "怀素（737—799年），唐代著名书法家，与张旭并称「颠张醉素」。俗姓钱，自幼出家为僧。好饮酒，醉后挥毫，如骤雨旋风，飞动圆转。怀素以狂草闻名，代表作《自叙帖》《苦笋帖》等，对后世草书影响深远。",
        "wu-dao-zi": "吴道子（约680—759年），唐代最杰出的画家，被尊为「画圣」。擅长佛道人物画，笔法超妙，气势磅礴。吴道子作画速度极快，有「吴带当风」之称，其画风对后世影响深远。与张旭草书、裴旻剑舞并称「唐代三绝」。",
    },
    new_persons=[
        {"slug": "du-ru-hui", "name": "杜如晦", "primaryRole": "minister",
         "roles": ["minister"], "importance": 85, "birthYear": 585,
         "deathYear": 630, "aliases": ["杜克明"],
         "summary": "唐朝开国功臣，房谋杜断，贞观之治缔造者之一。"},
        {"slug": "yao-chong", "name": "姚崇", "primaryRole": "minister",
         "roles": ["minister", "reformer"], "importance": 90, "birthYear": 651,
         "deathYear": 721, "aliases": ["姚元之"],
         "summary": "唐朝名相，提出十事要说，开创开元盛世。"},
        {"slug": "song-jing", "name": "宋璟", "primaryRole": "minister",
         "roles": ["minister"], "importance": 85, "birthYear": 663,
         "deathYear": 737, "aliases": ["宋广平"],
         "summary": "唐朝名相，刚正清廉，与姚崇并称姚宋，开创开元盛世。"},
        {"slug": "li-lin-fu", "name": "李林甫", "primaryRole": "minister",
         "roles": ["minister", "traitor"], "importance": 75, "birthYear": 683,
         "deathYear": 753, "aliases": ["口蜜腹剑"],
         "summary": "唐朝权相，口蜜腹剑，任相十九年，为安史之乱埋下祸根。"},
        {"slug": "yang-guo-zhong", "name": "杨国忠", "primaryRole": "minister",
         "roles": ["minister", "traitor"], "importance": 70, "deathYear": 756,
         "aliases": ["杨国忠"],
         "summary": "杨贵妃堂兄，唐朝权相，激化矛盾导致安史之乱。"},
        {"slug": "gao-li-shi", "name": "高力士", "primaryRole": "eunuch",
         "roles": ["eunuch", "minister"], "importance": 70, "birthYear": 684,
         "deathYear": 762, "aliases": ["高将军"],
         "summary": "唐朝宦官，唐玄宗最宠信的宦官，官至骠骑大将军。"},
        {"slug": "lai-jun-chen", "name": "来俊臣", "primaryRole": "official",
         "roles": ["official", "cruel"], "importance": 60, "birthYear": 651,
         "deathYear": 697, "aliases": ["来俊臣"],
         "summary": "唐朝酷吏，大兴告密之风，罗织罪名，制造大量冤案。"},
        {"slug": "zhang-xu", "name": "张旭", "primaryRole": "artist",
         "roles": ["artist", "calligrapher"], "importance": 80, "birthYear": 675,
         "deathYear": 750, "aliases": ["草圣", "张颠"],
         "summary": "唐代草圣，精通草书，与怀素并称颠张醉素。"},
        {"slug": "huai-su", "name": "怀素", "primaryRole": "artist",
         "roles": ["artist", "calligrapher", "monk"], "importance": 80,
         "birthYear": 737, "deathYear": 799, "aliases": ["藏真"],
         "summary": "唐代书法家，以狂草闻名，与张旭并称颠张醉素。"},
        {"slug": "wu-dao-zi", "name": "吴道子", "primaryRole": "artist",
         "roles": ["artist"], "importance": 90, "birthYear": 680,
         "deathYear": 759, "aliases": ["画圣"],
         "summary": "唐代画圣，擅长佛道人物画，吴带当风，唐代三绝之一。"},
    ],
    new_events=[
        {"slug": "gan-lu-zhi-bian", "name": "甘露之变", "timeStart": 835,
         "timeEnd": 835, "aliases": ["甘露之变"],
         "summary": "唐文宗欲诛宦官，事泄失败，宦官大肆屠杀朝臣。",
         "content": "835年，唐文宗不甘心受宦官控制，与宰相李训、郑注等密谋诛杀宦官。李训谎称金吾卫后院石榴树上夜降甘露，请宦官仇士良等前往观看，企图趁机诛杀。但事机不密，被仇士良发觉，宦官劫持唐文宗，大肆屠杀朝臣，李训、郑注等千余人被杀。甘露之变后，宦官完全控制朝政，唐朝皇帝成为傀儡。"},
        {"slug": "hui-chang-mie-fo", "name": "会昌灭佛", "timeStart": 845,
         "timeEnd": 846, "aliases": ["会昌法难"],
         "summary": "唐武宗推行灭佛政策，拆毁寺院、勒令僧尼还俗，打击佛教势力。",
         "content": "845年，唐武宗推行灭佛政策，下令拆毁寺院四千六百余所，勒令僧尼二十六万余人还俗，没收寺院田地数千万顷。会昌灭佛是「三武一宗灭佛」中规模最大的一次，沉重打击了佛教势力。灭佛的原因包括：寺院经济膨胀影响国家财政、佛教与道教之争、唐武宗崇信道教等。会昌灭佛对佛教在中国的发展产生了深远影响。"},
        {"slug": "da-zhong-zhi-zhi", "name": "大中之治", "timeStart": 847,
         "timeEnd": 860, "aliases": ["小太宗"],
         "summary": "唐宣宗在位期间，勤政爱民、整顿吏治，史称「大中之治」。",
         "content": "唐宣宗李忱在位期间（847—860年），勤于政事、明察秋毫，整顿吏治、打击藩镇，收复河湟失地，社会相对安定。唐宣宗被誉为「小太宗」，其统治时期史称「大中之治」。但唐宣宗刚愎自用、猜忌大臣，且迷信道教，服食丹药而死。大中之治是唐朝最后的回光返照，此后唐朝走向衰亡。"},
    ],
)

# ── 五代十国 ──────────────────────────────────────────────────────────────────
enrich(
    "wu-dai-shi-guo.json",
    person_content={
        "wang-jian": "王建（847—918年），前蜀开国皇帝。许州舞阳人，唐末忠武军将领。唐亡后割据四川，907年称帝，建国号蜀，史称前蜀。王建在位期间保境安民、发展经济，四川相对安定。但晚年荒淫无度，918年病死。",
        "yang-hang-mi": "杨行密（852—905年），吴国开国者。庐州合肥人，唐末淮南节度使。朱温篡唐后，杨行密割据淮南，建立吴国。在位期间发展经济、保境安民，使江淮地区免于战乱。杨行密是五代十国时期较有作为的君主之一。",
        "xu-wen": "徐温（862—927年），吴国权臣。原为杨行密部将，杨行密死后掌握吴国大权。徐温执政期间，继续推行保境安民政策，吴国国力得到发展。其养子徐知诰（李昪）后来代吴建南唐。",
        "liu-zhi-yuan": "刘知远（895—948年），后汉开国皇帝。沙陀族，原为后晋河东节度使。契丹灭后晋后，刘知远在太原称帝，建国号汉，史称后汉。在位仅一年即病死，其子刘承祐继位后被郭威所灭。",
        "shi-zhong-gui": "石重贵（914—974年），后晋出帝，石敬瑭之侄。石敬瑭死后继位，不甘心向契丹称臣，拒绝称孙，引发契丹南侵。946年契丹攻入开封，石重贵被俘虏北迁，后晋灭亡。石重贵在契丹被封为「负义侯」，客死异乡。",
    },
    new_persons=[
        {"slug": "wang-jian", "name": "王建", "primaryRole": "emperor",
         "roles": ["emperor"], "importance": 70, "birthYear": 847,
         "deathYear": 918, "aliases": ["前蜀高祖"],
         "summary": "前蜀开国皇帝，割据四川，保境安民，发展经济。"},
        {"slug": "yang-hang-mi", "name": "杨行密", "primaryRole": "emperor",
         "roles": ["emperor", "general"], "importance": 75, "birthYear": 852,
         "deathYear": 905, "aliases": ["吴太祖"],
         "summary": "吴国开国者，割据淮南，保境安民，使江淮免于战乱。"},
        {"slug": "xu-wen", "name": "徐温", "primaryRole": "regent",
         "roles": ["regent", "general"], "importance": 65, "birthYear": 862,
         "deathYear": 927, "aliases": ["徐温"],
         "summary": "吴国权臣，掌握吴国大权，推行保境安民政策。"},
        {"slug": "liu-zhi-yuan", "name": "刘知远", "primaryRole": "emperor",
         "roles": ["emperor", "general"], "importance": 65, "birthYear": 895,
         "deathYear": 948, "aliases": ["后汉高祖"],
         "summary": "后汉开国皇帝，沙陀族，在位仅一年即病死。"},
        {"slug": "shi-zhong-gui", "name": "石重贵", "primaryRole": "emperor",
         "roles": ["emperor"], "importance": 55, "birthYear": 914,
         "deathYear": 974, "aliases": ["后晋出帝"],
         "summary": "后晋出帝，拒绝向契丹称臣，被俘虏北迁，客死异乡。"},
    ],
    new_events=[],
)

print("\n✅ 南北朝隋唐五代补全完成！")
