from _lib import enrich

# ── 北宋 ──────────────────────────────────────────────────────────────────────
enrich(
    "bei-song.json",
    person_content={
        "bao-zheng": "包拯（999—1062年），字希仁，北宋名臣，「包青天」。庐州合肥人，进士出身。为官清廉刚正、执法如山，不畏权贵、铁面无私。任开封府尹时，开正门、许百姓直诉，人称「关节不到，有阎罗包老」。包拯是中国历史上最著名的清官，被后世神化为正义的化身。",
        "han-qi": "韩琦（1008—1075年），字稚圭，北宋名相。与范仲淹共同主持庆历新政，后又参与抵御西夏。韩琦历仕三朝，为相十年，以沉稳持重、善于调和著称。与富弼并称「韩富」，是北宋中期最重要的政治家之一。",
        "fu-bi": "富弼（1004—1083年），字彦国，北宋名相。以外交才能著称，曾出使辽国，以非凡的口才和智慧，不费一兵一卒，迫使辽国放弃领土要求。富弼与韩琦并称「韩富」，是北宋中期最重要的政治家之一。",
        "wen-yan-bo": "文彦博（1006—1097年），字宽夫，北宋名相。历仕四朝，任相五十年，以稳重老练著称。文彦博善于处理复杂的政治局面，在新旧党争中保持中立，是北宋政坛的常青树。",
        "lv-duan": "吕端（935—1000年），字易直，北宋名相。「吕端大事不糊涂」的典故由来。宋太宗欲立太子，吕端力主立真宗，避免了一场政治危机。吕端平时糊里糊涂，但遇到大事却非常精明，是北宋初期最贤明的宰相之一。",
        "yang-ye": "杨业（？—986年），又名杨继业，北宋抗辽名将，杨家将始祖。原为北汉将领，北汉亡后归宋。镇守边关，威震契丹，人称「杨无敌」。986年北伐时，因监军王侁逼迫，杨业孤军深入，兵败被俘，绝食而死。杨业的忠勇精神成为后世杨家将故事的原型。",
        "yang-yan-zhao": "杨延昭（958—1014年），杨业之子，北宋抗辽名将。继承父业，镇守边关二十余年，多次击败辽军。辽人惧之，呼为「杨六郎」（认为他是天上的六郎星下凡）。杨延昭是杨家将第二代的核心人物。",
        "mu-gui-ying": "穆桂英（约1000年），杨家女将，杨宗保之妻。传说穆桂英武艺超群、巾帼不让须眉，曾大破天门阵，立下赫赫战功。穆桂英是中国民间传说中最著名的女将之一，但正史中并无记载，主要来自小说和戏曲。",
        "bi-sheng": "毕昇（约970—1051年），北宋发明家，活字印刷术发明者。庆历年间（1041—1048年），毕昇发明胶泥活字印刷术，用胶泥刻字，火烧使之坚硬，排版印刷。活字印刷术是中国四大发明之一，比欧洲古腾堡早四百年，对世界文明发展产生了深远影响。",
        "shen-kuo": "沈括（1031—1095年），字存中，北宋杰出科学家。精通天文、数学、物理、化学、地理、医学等，著有《梦溪笔谈》，被誉为「中国科学史上的里程碑」。沈括发现磁偏角、发明十二气历、改进浑仪等，是中国古代最博学的科学家之一。",
        "cheng-hao": "程颢（1032—1085年），字伯淳，北宋理学家，与弟程颐并称「二程」。师从周敦颐，创立「天理」学说，主张「天者理也」「心即理」。程颢是北宋理学的奠基人之一，与程颐的学说合称「程朱理学」，对后世影响深远。",
        "cheng-yi": "程颐（1033—1107年），字正叔，北宋理学家，程颢之弟。与兄长共创「天理」学说，主张「格物致知」「存天理、灭人欲」。程颐是北宋理学的奠基人之一，其学说对南宋朱熹影响深远，合称「程朱理学」。",
        "huang-ting-jian": "黄庭坚（1045—1105年），字鲁直，号山谷道人，北宋著名书法家、诗人。与苏轼并称「苏黄」，是「宋四家」（苏黄米蔡）之一。书法以行书、草书著称，诗风奇崛瘦硬，开创江西诗派。黄庭坚是北宋最杰出的艺术家之一。",
        "mi-fu": "米芾（1051—1107年），字元章，号襄阳漫士，北宋著名书法家、画家。「宋四家」（苏黄米蔡）之一，以行书著称，风格独特，人称「米颠」。米芾嗜好奇石，见石辄拜，人称「米颠拜石」。其书画艺术对后世影响深远。",
        "cai-xiang": "蔡襄（1012—1067年），字君谟，北宋著名书法家。「宋四家」（苏黄米蔡）之一，以楷书、行书著称，风格端庄秀雅。蔡襄曾主持修建泉州洛阳桥（万安桥），是中国现存最早的跨海大桥。蔡襄不仅是书法家，还是茶学家，著有《茶录》。",
        "liu-yong": "柳永（987—1053年），字耆卿，北宋著名词人，婉约派代表。原名三变，因排行第七，又称柳七。柳永一生仕途坎坷，但词作流传极广，「凡有井水处，即能歌柳词」。代表作《雨霖铃》《八声甘州》等，对宋词发展影响深远。",
    },
    new_persons=[
        {"slug": "bao-zheng", "name": "包拯", "primaryRole": "minister",
         "roles": ["minister", "judge"], "importance": 95, "birthYear": 999,
         "deathYear": 1062, "aliases": ["包青天", "包希仁"],
         "summary": "北宋名臣，包青天，执法如山，铁面无私，中国最著名的清官。"},
        {"slug": "han-qi", "name": "韩琦", "primaryRole": "minister",
         "roles": ["minister"], "importance": 85, "birthYear": 1008,
         "deathYear": 1075, "aliases": ["韩稚圭"],
         "summary": "北宋名相，主持庆历新政，历仕三朝，沉稳持重。"},
        {"slug": "fu-bi", "name": "富弼", "primaryRole": "minister",
         "roles": ["minister", "diplomat"], "importance": 80, "birthYear": 1004,
         "deathYear": 1083, "aliases": ["富彦国"],
         "summary": "北宋名相，出使辽国，不费一兵一卒迫使辽国放弃领土要求。"},
        {"slug": "wen-yan-bo", "name": "文彦博", "primaryRole": "minister",
         "roles": ["minister"], "importance": 75, "birthYear": 1006,
         "deathYear": 1097, "aliases": ["文宽夫"],
         "summary": "北宋名相，历仕四朝，任相五十年，政坛常青树。"},
        {"slug": "lv-duan", "name": "吕端", "primaryRole": "minister",
         "roles": ["minister"], "importance": 75, "birthYear": 935,
         "deathYear": 1000, "aliases": ["吕易直"],
         "summary": "北宋名相，吕端大事不糊涂，力主立真宗。"},
        {"slug": "yang-ye", "name": "杨业", "primaryRole": "general",
         "roles": ["general", "hero"], "importance": 85, "deathYear": 986,
         "aliases": ["杨继业", "杨无敌"],
         "summary": "北宋抗辽名将，杨家将始祖，兵败被俘绝食而死。"},
        {"slug": "yang-yan-zhao", "name": "杨延昭", "primaryRole": "general",
         "roles": ["general"], "importance": 80, "birthYear": 958,
         "deathYear": 1014, "aliases": ["杨六郎"],
         "summary": "杨业之子，北宋抗辽名将，镇守边关二十余年。"},
        {"slug": "mu-gui-ying", "name": "穆桂英", "primaryRole": "general",
         "roles": ["general", "hero"], "importance": 70,
         "aliases": ["穆桂英"],
         "summary": "杨家女将，武艺超群，大破天门阵，巾帼不让须眉。"},
        {"slug": "bi-sheng", "name": "毕昇", "primaryRole": "inventor",
         "roles": ["inventor"], "importance": 90, "birthYear": 970,
         "deathYear": 1051, "aliases": ["毕昇"],
         "summary": "北宋发明家，发明活字印刷术，中国四大发明之一。"},
        {"slug": "shen-kuo", "name": "沈括", "primaryRole": "scientist",
         "roles": ["scientist", "minister"], "importance": 90, "birthYear": 1031,
         "deathYear": 1095, "aliases": ["沈存中"],
         "summary": "北宋杰出科学家，著《梦溪笔谈》，中国科学史上的里程碑。"},
        {"slug": "cheng-hao", "name": "程颢", "primaryRole": "philosopher",
         "roles": ["philosopher"], "importance": 85, "birthYear": 1032,
         "deathYear": 1085, "aliases": ["程伯淳", "明道先生"],
         "summary": "北宋理学家，与弟程颐并称二程，理学奠基人之一。"},
        {"slug": "cheng-yi", "name": "程颐", "primaryRole": "philosopher",
         "roles": ["philosopher"], "importance": 85, "birthYear": 1033,
         "deathYear": 1107, "aliases": ["程正叔", "伊川先生"],
         "summary": "北宋理学家，程颢之弟，理学奠基人之一，格物致知。"},
        {"slug": "huang-ting-jian", "name": "黄庭坚", "primaryRole": "artist",
         "roles": ["artist", "poet"], "importance": 85, "birthYear": 1045,
         "deathYear": 1105, "aliases": ["黄鲁直", "山谷道人"],
         "summary": "北宋书法家、诗人，宋四家之一，开创江西诗派。"},
        {"slug": "mi-fu", "name": "米芾", "primaryRole": "artist",
         "roles": ["artist"], "importance": 85, "birthYear": 1051,
         "deathYear": 1107, "aliases": ["米元章", "米颠"],
         "summary": "北宋书法家、画家，宋四家之一，米颠拜石。"},
        {"slug": "cai-xiang", "name": "蔡襄", "primaryRole": "artist",
         "roles": ["artist", "engineer"], "importance": 75, "birthYear": 1012,
         "deathYear": 1067, "aliases": ["蔡君谟"],
         "summary": "北宋书法家，宋四家之一，主持修建洛阳桥。"},
        {"slug": "liu-yong", "name": "柳永", "primaryRole": "poet",
         "roles": ["poet"], "importance": 80, "birthYear": 987,
         "deathYear": 1053, "aliases": ["柳七", "柳耆卿"],
         "summary": "北宋词人，婉约派代表，凡有井水处即能歌柳词。"},
    ],
    new_events=[
        {"slug": "yang-jiang-kang-liao", "name": "杨家将抗辽", "timeStart": 979,
         "timeEnd": 1005, "aliases": ["杨家将"],
         "summary": "杨业、杨延昭父子镇守边关，抵御辽国入侵，威震契丹。",
         "content": "北宋初期，杨业、杨延昭父子镇守北方边关，抵御辽国入侵。杨业号称「杨无敌」，多次击败辽军。986年北伐时，杨业孤军深入，兵败被俘，绝食而死。其子杨延昭继承父业，镇守边关二十余年，辽人呼为「杨六郎」。杨家将的忠勇精神成为后世文学艺术的重要题材，被演绎成各种小说、戏曲、影视作品。"},
        {"slug": "huo-zi-yin-shua-shu", "name": "活字印刷术发明", "timeStart": 1041,
         "timeEnd": 1048, "aliases": ["活字印刷"],
         "summary": "毕昇发明活字印刷术，用胶泥刻字排版印刷，比欧洲早四百年。",
         "content": "庆历年间（1041—1048年），北宋平民毕昇发明胶泥活字印刷术。他用胶泥刻字，火烧使之坚硬，然后排版印刷。印完后可拆版重印，大大提高了印刷效率。活字印刷术是中国四大发明之一，比欧洲古腾堡早四百年，对世界文明发展产生了深远影响。沈括《梦溪笔谈》详细记载了毕昇的发明。"},
        {"slug": "jiao-zi-chu-xian", "name": "交子的出现", "timeStart": 1024,
         "timeEnd": 1024, "aliases": ["交子"],
         "summary": "北宋出现世界上最早的纸币交子，是中国金融史上的重大发明。",
         "content": "1024年，北宋四川地区出现世界上最早的纸币「交子」。最初由民间商人自发发行，用于代替沉重的铁钱流通。后由官方接管发行，设立交子务管理。交子的出现是中国金融史上的重大发明，比欧洲纸币早六百余年。交子的发明反映了北宋商品经济的繁荣和金融创新。"},
    ],
)

# ── 南宋 ──────────────────────────────────────────────────────────────────────
enrich(
    "nan-song.json",
    person_content={
        "zhao-shen": "赵昚（1127—1194年），宋孝宗，南宋最有作为的皇帝。即位后为岳飞平反，起用主战派，发动隆兴北伐。虽北伐失败，但与金国签订「隆兴和议」，改称臣为称侄，地位有所提高。孝宗在位期间政治清明、经济繁荣，史称「乾淳之治」，是南宋最繁荣的时期。",
        "han-tuo-zhou": "韩侂胄（1152—1207年），南宋权臣。以外戚身份掌权，追封岳飞、贬斥秦桧，力主北伐。1206年发动「开禧北伐」，但准备不足、用人不当，北伐失败。韩侂胄被主和派杀害，首级送往金国求和。韩侂胄是南宋中期最重要的政治人物之一。",
        "shi-mi-yuan": "史弥远（1164—1233年），南宋权臣。韩侂胄死后继任宰相，独揽朝政二十六年。史弥远专权期间，政治腐败、民不聊生，南宋国势日衰。史弥远是南宋后期最专权的宰相，与秦桧、韩侂胄并称南宋三大权臣。",
        "jia-si-dao": "贾似道（1213—1275年），南宋末年权臣。以姐姐为宋理宗贵妃而得势，后任宰相。鄂州之战中，贾似道擅自与蒙古议和，谎报大捷。后独揽朝政，推行「公田法」，搜刮民财。元军南侵时，贾似道兵败丁家洲，被贬斥，途中被杀。贾似道误国是南宋灭亡的重要原因。",
        "yu-yun-wen": "虞允文（1110—1174年），南宋名臣。1161年采石之战中，虞允文以文臣身份督师，指挥宋军大败金军，取得采石大捷。此战扭转了南宋的被动局面，金国从此无力南侵。虞允文后任宰相，力主北伐，是南宋中期最重要的主战派大臣。",
        "wu-jie": "吴玠（1093—1139年），南宋抗金名将。与弟吴璘镇守川陕，多次击败金军进攻。和尚原之战、仙人关之战中大败金军，保住四川。吴玠是南宋初期最重要的军事将领之一，与岳飞、韩世忠并称南宋抗金三大名将。",
        "liu-qi": "刘锜（1098—1162年），南宋抗金名将。1140年顺昌之战中，刘锜以两万兵力大败金兀术十万大军，取得顺昌大捷。此战是南宋抗金战争中最辉煌的胜利之一，刘锜因此威名远震。",
        "lu-jiu-ling": "陆九龄（1132—1180年），南宋理学家，陆九渊之兄。与弟陆九渊共创「心学」，主张「心即理」。陆九龄学问渊博、品德高尚，与弟陆九渊并称「二陆」。",
        "zhang-shi": "张栻（1133—1180年），南宋理学家，张浚之子。师从胡宏，与朱熹、吕祖谦并称「东南三贤」。主持岳麓书院，弘扬理学，对南宋学术发展影响深远。张栻是湖湘学派的代表人物。",
        "lv-zu-qian": "吕祖谦（1137—1181年），南宋理学家。与朱熹、张栻并称「东南三贤」。学问渊博，兼采众长，主张「明理躬行」。编纂《宋文鉴》，对宋代文学研究贡献巨大。吕祖谦是南宋最重要的学者之一。",
    },
    new_persons=[
        {"slug": "zhao-shen", "name": "赵昚", "primaryRole": "emperor",
         "roles": ["emperor"], "importance": 85, "birthYear": 1127,
         "deathYear": 1194, "aliases": ["宋孝宗"],
         "summary": "南宋最有作为的皇帝，为岳飞平反，发动隆兴北伐，乾淳之治。"},
        {"slug": "han-tuo-zhou", "name": "韩侂胄", "primaryRole": "minister",
         "roles": ["minister", "reformer"], "importance": 75, "birthYear": 1152,
         "deathYear": 1207, "aliases": ["韩侂胄"],
         "summary": "南宋权臣，追封岳飞、发动开禧北伐，失败被杀。"},
        {"slug": "shi-mi-yuan", "name": "史弥远", "primaryRole": "minister",
         "roles": ["minister", "traitor"], "importance": 70, "birthYear": 1164,
         "deathYear": 1233, "aliases": ["史弥远"],
         "summary": "南宋权臣，独揽朝政二十六年，政治腐败。"},
        {"slug": "jia-si-dao", "name": "贾似道", "primaryRole": "minister",
         "roles": ["minister", "traitor"], "importance": 70, "birthYear": 1213,
         "deathYear": 1275, "aliases": ["贾似道"],
         "summary": "南宋末年权臣，误国害民，兵败被杀，南宋灭亡的重要原因。"},
        {"slug": "yu-yun-wen", "name": "虞允文", "primaryRole": "minister",
         "roles": ["minister", "general"], "importance": 85, "birthYear": 1110,
         "deathYear": 1174, "aliases": ["虞彬父"],
         "summary": "南宋名臣，采石之战大败金军，扭转南宋被动局面。"},
        {"slug": "wu-jie", "name": "吴玠", "primaryRole": "general",
         "roles": ["general", "hero"], "importance": 85, "birthYear": 1093,
         "deathYear": 1139, "aliases": ["吴晋卿"],
         "summary": "南宋抗金名将，镇守川陕，和尚原、仙人关大败金军。"},
        {"slug": "liu-qi", "name": "刘锜", "primaryRole": "general",
         "roles": ["general"], "importance": 80, "birthYear": 1098,
         "deathYear": 1162, "aliases": ["刘信叔"],
         "summary": "南宋抗金名将，顺昌大捷，以两万兵力大败金兀术十万大军。"},
        {"slug": "lu-jiu-ling", "name": "陆九龄", "primaryRole": "philosopher",
         "roles": ["philosopher"], "importance": 70, "birthYear": 1132,
         "deathYear": 1180, "aliases": ["陆子寿"],
         "summary": "南宋理学家，陆九渊之兄，与弟共创心学。"},
        {"slug": "zhang-shi", "name": "张栻", "primaryRole": "philosopher",
         "roles": ["philosopher", "educator"], "importance": 75, "birthYear": 1133,
         "deathYear": 1180, "aliases": ["张敬夫", "南轩先生"],
         "summary": "南宋理学家，主持岳麓书院，与朱熹、吕祖谦并称东南三贤。"},
        {"slug": "lv-zu-qian", "name": "吕祖谦", "primaryRole": "philosopher",
         "roles": ["philosopher", "scholar"], "importance": 75, "birthYear": 1137,
         "deathYear": 1181, "aliases": ["吕伯恭"],
         "summary": "南宋理学家，与朱熹、张栻并称东南三贤，编纂《宋文鉴》。"},
    ],
    new_events=[
        {"slug": "cai-shi-zhi-zhan", "name": "采石之战", "timeStart": 1161,
         "timeEnd": 1161, "aliases": ["采石大捷"],
         "summary": "虞允文指挥宋军大败金军于采石矶，扭转南宋被动局面。",
         "content": "1161年，金国皇帝完颜亮率六十万大军南侵，企图一举灭宋。宋军主将王权逃跑，军心涣散。中书舍人虞允文以文臣身份督师，在采石矶（今安徽马鞍山）指挥宋军大败金军。完颜亮被迫撤退，后被部下杀死。采石之战扭转了南宋的被动局面，金国从此无力南侵。"},
        {"slug": "long-xing-bei-fa", "name": "隆兴北伐", "timeStart": 1163,
         "timeEnd": 1164, "aliases": ["隆兴北伐"],
         "summary": "宋孝宗发动北伐，企图收复中原，但准备不足，最终失败。",
         "content": "1163年，宋孝宗即位后，为岳飞平反，起用主战派张浚，发动隆兴北伐。宋军一度收复灵璧、虹县等地，但在符离之战中大败。孝宗被迫与金国签订「隆兴和议」，改称臣为称侄，岁贡改为岁币，地位有所提高。隆兴北伐虽然失败，但改善了南宋的国际地位。"},
        {"slug": "kai-xi-bei-fa", "name": "开禧北伐", "timeStart": 1206,
         "timeEnd": 1208, "aliases": ["开禧北伐"],
         "summary": "韩侂胄发动北伐，但准备不足、用人不当，最终失败。",
         "content": "1206年，权臣韩侂胄追封岳飞、贬斥秦桧，发动开禧北伐。但准备不足、用人不当，宋军节节败退。韩侂胄被主和派史弥远杀害，首级送往金国求和。南宋被迫签订「嘉定和议」，岁币增至三十万，赔款三百万两。开禧北伐的失败，使南宋彻底丧失了北伐的信心。"},
        {"slug": "jia-si-dao-wu-guo", "name": "贾似道误国", "timeStart": 1259,
         "timeEnd": 1275, "aliases": ["贾似道专权"],
         "summary": "贾似道独揽朝政，推行公田法，搜刮民财，加速南宋灭亡。",
         "content": "1259年鄂州之战，贾似道擅自与蒙古议和，谎报大捷，以此获得宋理宗信任，独揽朝政。贾似道推行「公田法」，强制收购地主土地，搜刮民财。又排斥异己、堵塞言路，政治日益腐败。1275年元军南侵，贾似道兵败丁家洲，被贬斥，途中被杀。贾似道误国是南宋灭亡的重要原因。"},
    ],
)

# ── 元朝 ──────────────────────────────────────────────────────────────────────
enrich(
    "yuan.json",
    person_content={
        "cha-han-tie-mu-er": "察罕帖木儿（？—1362年），元末名将。颍州沈丘人，畏兀儿族。红巾军起义后，察罕帖木儿组织地主武装，转战中原，多次击败红巾军，收复汴梁，威震天下。后被降将田丰、王士诚刺杀。察罕帖木儿是元末最重要的将领之一，他的死使元朝丧失了最后的希望。",
        "kuo-kuo-tie-mu-er": "扩廓帖木儿（？—1375年），察罕帖木儿养子，元末名将。继承父业，继续与红巾军作战。元朝灭亡后，扩廓帖木儿退守漠北，继续抵抗明朝。朱元璋曾多次派人招降，均被拒绝。扩廓帖木儿是元末明初最顽强的抵抗者，被称为「奇男子」。",
        "zhang-shi-cheng": "张士诚（1321—1367年），元末割据势力。泰州白驹场人，盐贩出身。1353年起兵反元，占据江浙一带，建国号吴。张士诚据有江南富庶之地，但沉迷享乐、不思进取。1367年被朱元璋击败，自缢而死。",
        "chen-you-liang": "陈友谅（1320—1363年），元末割据势力。沔阳人，渔家出身。红巾军将领，后杀徐寿辉自立为帝，建国号汉，占据长江中游。鄱阳湖之战中与朱元璋决战，兵败中箭而死。陈友谅是朱元璋最强大的对手之一。",
        "ming-yu-zhen": "明玉珍（1331—1366年），元末割据势力。随州人，红巾军将领。1357年入川，占据四川，建国号夏。明玉珍在位期间保境安民、发展经济，四川相对安定。死后其子明升降明，四川归入明朝版图。",
        "huang-dao-po": "黄道婆（约1245—1330年），元代纺织技术革新家。松江乌泥泾人，年轻时流落崖州（今海南），向黎族学习纺织技术。返回家乡后，改良纺织工具，传授先进技艺，使松江成为全国棉纺织中心。黄道婆是中国古代最杰出的女性科技人才之一。",
        "ma-zhi-yuan": "马致远（约1250—1321年），元代杂剧作家，「元曲四大家」之一。号东篱，大都人。代表作《汉宫秋》《青衫泪》等，散曲《天净沙·秋思》「枯藤老树昏鸦」传诵千古。马致远是元代最杰出的散曲作家之一。",
        "bai-pu": "白朴（1226—约1306年），元代杂剧作家，「元曲四大家」之一。字太素，号兰谷，隩州人。代表作《梧桐雨》《墙头马上》等，以文采著称。白朴是元代最重要的杂剧作家之一。",
        "zheng-guang-zu": "郑光祖（？—约1324年），元代杂剧作家，「元曲四大家」之一。字德辉，平阳人。代表作《倩女离魂》《王粲登楼》等，以词藻华丽著称。郑光祖是元代后期最重要的杂剧作家。",
    },
    new_persons=[
        {"slug": "cha-han-tie-mu-er", "name": "察罕帖木儿", "primaryRole": "general",
         "roles": ["general"], "importance": 80, "deathYear": 1362,
         "aliases": ["察罕"],
         "summary": "元末名将，多次击败红巾军，收复汴梁，后被刺杀。"},
        {"slug": "kuo-kuo-tie-mu-er", "name": "扩廓帖木儿", "primaryRole": "general",
         "roles": ["general"], "importance": 75, "deathYear": 1375,
         "aliases": ["王保保"],
         "summary": "元末名将，察罕帖木儿养子，退守漠北继续抵抗明朝。"},
        {"slug": "zhang-shi-cheng", "name": "张士诚", "primaryRole": "warlord",
         "roles": ["warlord", "emperor"], "importance": 75, "birthYear": 1321,
         "deathYear": 1367, "aliases": ["张九四"],
         "summary": "元末割据势力，占据江浙，建国号吴，后被朱元璋击败。"},
        {"slug": "chen-you-liang", "name": "陈友谅", "primaryRole": "warlord",
         "roles": ["warlord", "emperor"], "importance": 80, "birthYear": 1320,
         "deathYear": 1363, "aliases": ["陈友谅"],
         "summary": "元末割据势力，建国号汉，鄱阳湖之战败于朱元璋。"},
        {"slug": "ming-yu-zhen", "name": "明玉珍", "primaryRole": "warlord",
         "roles": ["warlord", "emperor"], "importance": 65, "birthYear": 1331,
         "deathYear": 1366, "aliases": ["明玉珍"],
         "summary": "元末割据势力，占据四川，建国号夏，保境安民。"},
        {"slug": "huang-dao-po", "name": "黄道婆", "primaryRole": "inventor",
         "roles": ["inventor"], "importance": 75, "birthYear": 1245,
         "deathYear": 1330, "aliases": ["黄婆"],
         "summary": "元代纺织技术革新家，改良纺织工具，使松江成为棉纺织中心。"},
        {"slug": "ma-zhi-yuan", "name": "马致远", "primaryRole": "playwright",
         "roles": ["playwright", "poet"], "importance": 80, "birthYear": 1250,
         "deathYear": 1321, "aliases": ["马东篱"],
         "summary": "元曲四大家之一，《天净沙·秋思》传诵千古。"},
        {"slug": "bai-pu", "name": "白朴", "primaryRole": "playwright",
         "roles": ["playwright"], "importance": 75, "birthYear": 1226,
         "deathYear": 1306, "aliases": ["白太素"],
         "summary": "元曲四大家之一，代表作《梧桐雨》《墙头马上》。"},
        {"slug": "zheng-guang-zu", "name": "郑光祖", "primaryRole": "playwright",
         "roles": ["playwright"], "importance": 70, "deathYear": 1324,
         "aliases": ["郑德辉"],
         "summary": "元曲四大家之一，代表作《倩女离魂》。"},
    ],
    new_events=[
        {"slug": "po-yang-hu-zhi-zhan", "name": "鄱阳湖之战", "timeStart": 1363,
         "timeEnd": 1363, "aliases": ["鄱阳湖大战"],
         "summary": "朱元璋与陈友谅决战鄱阳湖，陈友谅兵败中箭而死。",
         "content": "1363年，朱元璋与陈友谅决战于鄱阳湖。陈友谅拥有六十万大军、巨型战舰，兵力远超朱元璋。但朱元璋采用火攻战术，利用风势焚烧陈友谅战舰。激战三十六天，陈友谅兵败，中箭而死。鄱阳湖之战是朱元璋统一全国的关键战役，此战后陈友谅势力瓦解，朱元璋成为南方最强大的势力。"},
    ],
)

print("\n✅ 宋元补全完成！")
